config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources:posts,exept:[:new] do
    resource:favorites,only:[:create,:destroy]
    resource:comments,only:[:create,:destroy]
  end
  resources:tags,only:[:show]
  root to:"homes#top"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to:post
  belongs_to:user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to:user
  belongs_to:post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to:user
  attachment:image
  has_many:favorites,dependent: :destroy
  has_many:comments,dependent: :destroy
  has_many:tag_maps,dependent: :destroy
  has_many:tags,through: :tag_maps,source: :tag
  def favorite_by(user)
    favorites.where(user_id:user.id).exists?
  end
  
  def save_tag(sent_tags)
    current_tags=self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags=current_tags-sent_tags
    new_tags=sent_tags-current_tags
    
    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name:old)
    end
    new_tags.each do |new|
      new_review_tag=Tag.find_or_initialize_by(tag_name:new)
      self.tags << new_review_tag
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many:tag_maps,dependent: :destroy
  has_many:posts,through: :tag_maps,source: :post
  paginates_per 3
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to:post
  belongs_to:tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:posts,dependent: :destroy
  has_many:favorites,dependent: :destroy
  has_many:comments,dependent: :destroy
  
  def favorite_by(user)
    favorites.where(user_id:user.id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action:configure_permitted_parameters,if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
  end
  def tag_list
    @tags = Tag.order(created_at: :desc).page(params[:page])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post=Post.find(params[:post_id])
    @comment=Comment.new
    comment=current_user.comments.new(comment_params)
    comment.post_id=@post.id
    comment.save
  end
  def destroy
  end
  
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action:find_post
  
  def create
    favorite=current_user.favorites.new(post_id:@post.id)
    favorite.save
  end
  
  def destroy
    favorite=current_user.favorites.find_by(post_id:@post.id)
    favorite.destroy
  end
  
  private
  def find_post
    @post=Post.find(params[:post_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @tags = Tag.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action:tag_list
  def index
    @post=Post.new
    @posts=Post.all
    @gourmand_posts=Post.where(kind:"グルメ")
    @fashion_posts=Post.where(kind:"ファッション")
    @travel_posts=Post.where(kind:"観光")
    @experience_posts=Post.where(kind:"体験")

  end
  def create
    post=current_user.posts.new(post_params)
    tag_list=params[:post][:tag_name].split("、")
    if post.save
      post.save_tag(tag_list)
      redirect_back(fallback_location:root_path)
    else
      redirect_back(fallback_location:root_path)
    end    
  end
  def destroy
    post=Post.find(params[:id])
    post.tags.each do |tag|
      if TagMap.where(tag_id:tag.id).count==1
        tag.destroy
      end
    end
    post.destroy
    redirect_to posts_path
  end
  
  def show
    @post=Post.find(params[:id])
    @comment=Comment.new
  end
  private
  def post_params
    params.require(:post).permit(:title,:body,:image,:kind)
  end
  def tag_list
    @tags = Tag.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag=Tag.find(params[:id])
    @tags = Tag.order(created_at: :desc).page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <div class="mb-3">
    <%= comment.user.name %><%= comment.created_at.strftime("%Y/%m/%d") %><br>
    <%= comment.comment %>
  </div>
<% end %>

app/views/comments/_new.html.erb
<%= form_with model:comment,url:post_comments_path(post.id) do |f| %>
  <%= f.text_field:comment,placeholder:"コメント入力",class:"form-controll" %>
  <%= f.submit "コメントする",class:"btn btn-success" %>
<% end %>

app/views/comments/create.js.erb
$(".comment-index").html("<%= j(render "comments/index", comments: @post.comments) %>");
$(".new-comment").html("<%= j(render "comments/new",comment: @comment, post: @post) %>" );

app/views/favorites/_fav.html.erb
<% if post.favorite_by(current_user) %>
  <%= link_to post_favorites_path(post.id),remote:true,method: :delete do %>
    <i class="fas fa-heart"></i><%= post.favorites.count %>
  <% end %>
<% else %>
  <%= link_to post_favorites_path(post.id),remote:true,method: :post do %>
    <i class="far fa-heart"></i><%= post.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$(".fav-btn-<%= @post.id %>").html("<%= j(render "favorites/fav",post:@post) %>");

app/views/favorites/destroy.js.erb
$(".fav-btn-<%= @post.id %>").html("<%= j(render "favorites/fav",post:@post) %>");

app/views/homes/top.html.erb
<div class="top">
  <div class="top-content">
    <div class="to-index bg-light">
      <h1>|埼玉県の良さを発信しよう！</h1>
      <div class="to-content">
        <i class="far fa-hand-point-right fa-3x"></i>
        <h2><%= link_to "投稿をする/見る",posts_path,type:"button",class:"btn btn-success" %></h2>
      </div>
    </div>
    <div class="bg-light">
    <h1>|埼玉県ってどんなところ？</h1>
    <div class="top-message">
      <div class="top-image">
        <%= image_tag 'kobaton.png',:size=>'400x300' %>
        <p class="kobaton">埼玉県マスコット「コバトン」</p>
      </div>
      <div class="top-text">
        <h2>首都・東京に隣接する埼玉<br>
        災害が少ないという恵まれた環境のもと<br>
        住み良い暮らし、活発な経済活動が行われています。
        </h2>
      </div>
    </div>
    </div>
  </div>
  
  <div class="top-box">
    <div class="main-box">
      <div class="box-content"><i class="fas fa-building fa-3x"></i><h2>経済</h2><p>平成30年度の県内総生産は23兆2541億円で全国5位、シェアで4.1％です。</p></div>
      <div class="box-content"><i class="fas fa-train fa-3x"></i><h2>充実の鉄道網</h2><p>県内の鉄道駅総数は228駅。東日本旅客鉄道、東武鉄道、西武鉄道、東京地下鉄、秩父鉄道、埼玉高速鉄道、首都圏新都心鉄道、さいたま新都心交通の8事業、24路線あります。</p></div>
    </div>
    <div class="main-box">
      <div class="box-content"><i class="fas fa-users fa-3x"></i><h2>人口</h2><p>約734万人が暮らし、人口増加率は全国4位、生産年齢人口の割合は60.8%で全国4位となっています。</p></div>
      <div class="box-content"><i class="fas fa-car fa-3x"></i><h2>充実の道路網</h2><p>圏央道、外環道、関越道、東北道、常盤道、首都高の充実した高速道路ネットワークがある埼玉県は、交通の要衝として有憂性が大きく向上しています。</p></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saitama</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://fonts.googleapis.com/css?family=Sawarabi+Mincho" rel="stylesheet">


    <script src="https://kit.fontawesome.com/12120b9d9d.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div id="wrapper">
    <div id="sidebar" class="close bg-light">
      <div class="tag_lists">
        <h2>タグ一覧</h2>
        <div class="tag-title">
          <%= render "posts/tag_list",tags:@tags %>
        </div>
        <button class="more">
          <%= link_to_next_page @tags,"もっと見る",remote:true,id:"view_more" %>
        </button>
      </div>
    </div>
    <div id="main">
      <nav class="navbar bg-light shadow-sm">
        <button type="button" id="sidebarCollapse" class="btn">
          <i class="fa fa-angle-double-right fa-2x sidebar-icon"></i>
        </button>
        <%= link_to root_path, class:"saitama-icon" do %><%= image_tag 'saitama.png',:size=>'140x80' %><% end %>
        <%= link_to "ログイン",new_user_session_path %>
        <%= link_to "ログアウト",destroy_user_session_path %>
      </nav>
    
      <body>
        <%= yield %>
      </body>
    </div>
  </div>
</html>

app/views/posts/_index.html.erb
<% if posts.present? %>
    <% posts.each do |post| %>
      <div class="card" style="width: 200px;">
        <%= attachment_image_tag post,:image,fallback:"noimage.png",size:'200x250',class:"bd-placeholder-img card-img-top w-100" %>
        <div class="card-body">
          <h5 class="card-title"><%= post.title %></h5>
          <p class="card-text"><%= post.kind %></p>
          <p class="card-text"><%= post.body %></p>
          <div class="fav-btn-<%= post.id %>">
            <%= render "favorites/fav",post:post %>
          </div>
          <%= link_to "詳細",post_path(post.id),class:"btn btn-primary btn-sm" %>
          <% if post.user_id === current_user.id %>
            <%= link_to "削除",post_path(post.id),method: :delete,class:"btn btn-danger btn-sm","data-confirm"=>"本当に削除していいですか？" %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>投稿はまだありません</p>
  <% end %>

app/views/posts/_tag_list.html.erb
<% tags.each do |tag| %>
  <div class="tag_name">
    <%= link_to tag_path(tag.id) do %><%= tag.tag_name %> <%= tag.posts.count %><% end %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="index-content">
  <div class="new-post bg-light" >
    <%= form_with model:@post,local:true do |f| %>
      <%= f.label:title %>
      <%= f.text_field:title,placeholder:"菓子屋横丁",class:"form-control" %>
      <%= f.label:category %>
      <%= f.select:kind,[["グルメ","グルメ"],["観光","観光"],["ファッション","ファッション"],["体験","体験"]],{},class:"form-control" %>
      <%= f.label:label %>
      <%= f.text_field:tag_name,placeholder:"全角カンマ（、）で区切って複数入力可",class:"form-control" %>
      <%= f.label:body %>
      <%= f.text_area:body,placeholder:"風情のある街並みで散策",class:"form-control" %>
      <%= f.label:image %>
      <%= f.attachment_field:image %>
      <%= f.submit "投稿",class:"btn btn-primary mt-3" %>
    <% end %>
  </div>
  <div class="post">
    <div class="tab">
      <div class="tab-bar tab-active">すべて</div>
      <div class="tab-bar">グルメ</div>
      <div class="tab-bar">観光</div>
      <div class="tab-bar">ファッション</div>
      <div class="tab-bar">体験</div>
    </div>
    <div class="post-index box-show bg-light">
      <%= render "posts/index",posts:@posts %>
    </div>
    <div class="post-index bg-light">
      <%= render "posts/index",posts:@gourmand_posts %>
    </div>
    <div class="post-index bg-light">
      <%= render "posts/index",posts:@travel_posts %>
    </div>
    <div class="post-index bg-light">
      <%= render "posts/index",posts:@fashion_posts %>
    </div>
    <div class="post-index bg-light">
      <%= render "posts/index",posts:@experience_posts %>
    </div>
  </div>
</div>

app/views/posts/index.js.erb
$(".tag-title").append("<%= j(render "posts/tag_list",tags:@tags) %>");
$("#view_more").replaceWith("<%= j( 
link_to_next_page(@tags, 'もっと見る', remote: true, id: 'view_more')) %>");

app/views/posts/show.html.erb
<div class="post-show">
  <div class="card" style="width: 500px;">
    <%= attachment_image_tag @post,:image,fallback:"noimage.png",size:'400x550',class:"bd-placeholder-img card-img-top w-100" %>
    <div class="card-body">
      <h5 class="card-title">
        <div class="tag-title">
          <div><%= @post.title %></div>
          <% @post.tags.each do |tag| %>
          　<div class="tag_name" %><%= tag.tag_name %></div>
          <% end %>
        </div>
      </h5>
      <p><%= @post.body %></p>
      <% if @post.favorite_by(current_user) %>
        <%= link_to post_favorites_path(@post.id),method: :delete do %>
          <i class="fas fa-heart"></i>
        <% end %>
      <% else %>
        <%= link_to post_favorites_path(@post.id),method: :post do %>
          <i class="far fa-heart"></i>
        <% end %>
      <% end %>
      <% if @post.user_id === current_user.id %>
        <%= link_to "削除",post_path(@post.id),method: :delete,class:"btn btn-danger btn-sm","data-confirm"=>"本当に削除していいですか？" %>
      <% end %>
    </div>
  </div>
  <div class="comment">
    <h2>コメント一覧</h2>
    <div class="comment-index">
      <%= render "comments/index", comments:@post.comments %>
    </div>
    <div class="new-comment">
      <%= render "comments/new", post:@post,comment:@comment %>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
    
  <div class="post-index box-show bg-light">
    <%= render "posts/index",posts:@tag.posts %>
  </div>

app/views/tags/show.js.erb
$(".tag-title").append("<%= j(render "posts/tag_list",tags:@tags) %>");
$("#view_more").replaceWith("<%= j( 
link_to_next_page(@tags, 'もっと見る', remote: true, id: 'view_more')) %>");